"""Analyze downloaded corpora and export reproducible summaries and charts."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import matplotlib
import pandas as pd

matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from helpdeskai.corpus.analysis import (  # noqa: E402
    add_conversation_metrics,
    add_text_length,
    dataframe_overview,
    document_duplicate_groups,
    load_corpora,
)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data/raw"))
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("docs/corpus_preparation"),
    )
    return parser.parse_args(argv)


def _describe(dataframe: pd.DataFrame, columns: list[str]) -> dict[str, Any]:
    return json.loads(dataframe[columns].describe().to_json())


def analyze_corpora(data_dir: Path) -> tuple[dict[str, Any], dict[str, pd.DataFrame]]:
    """Calculate corpus quality, length, distribution, and duplicate summaries."""
    corpora = load_corpora(data_dir)
    techqa_qa = add_text_length(corpora["techqa_qa"], "question", "question_length")
    techqa_qa = add_text_length(techqa_qa, "answer", "answer_length")
    techqa_documents = add_text_length(
        corpora["techqa_documents"],
        "document",
        "document_length",
    )
    bitext = add_text_length(corpora["bitext"], "instruction", "instruction_length")
    bitext = add_text_length(bitext, "response", "response_length")
    msdialog = add_conversation_metrics(corpora["msdialog"])
    duplicate_groups = document_duplicate_groups(techqa_documents)

    summary = {
        "overview": dataframe_overview(corpora).reset_index().to_dict(orient="records"),
        "techqa": {
            "split_counts": techqa_qa["split"].value_counts().to_dict(),
            "lengths": _describe(
                techqa_qa,
                ["question_length", "answer_length"],
            ),
            "document_lengths": _describe(techqa_documents, ["document_length"]),
            "duplicate_groups": len(duplicate_groups),
            "duplicate_rows_removed": int(
                duplicate_groups["duplicate_rows_removed"].sum()
            ),
            "cross_split_duplicate_groups": int(duplicate_groups["cross_split"].sum()),
        },
        "bitext": {
            "category_counts": bitext["category"].value_counts().to_dict(),
            "intent_counts": bitext["intent"].value_counts().to_dict(),
            "lengths": _describe(
                bitext,
                ["instruction_length", "response_length"],
            ),
        },
        "msdialog": {
            "metrics": _describe(
                msdialog,
                ["turn_count", "conversation_char_length"],
            ),
        },
    }
    prepared = {
        "techqa_qa": techqa_qa,
        "techqa_documents": techqa_documents,
        "bitext": bitext,
        "msdialog": msdialog,
    }
    return summary, prepared


def write_analysis(
    output_dir: Path,
    summary: dict[str, Any],
    frames: dict[str, pd.DataFrame],
) -> list[Path]:
    """Write JSON, Markdown, and PNG analysis artifacts."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "corpus_analysis.json"
    markdown_path = output_dir / "corpus_analysis.md"
    lengths_path = output_dir / "corpus_length_distributions.png"
    bitext_path = output_dir / "bitext_distributions.png"

    json_path.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    overview_rows = summary["overview"]
    overview = "\n".join(
        [
            "| Dataset | Rows | Columns | Missing values | Duplicate rows |",
            "| --- | ---: | ---: | ---: | ---: |",
            *[
                f"| {row['dataset']} | {row['rows']} | {row['columns']} | "
                f"{row['missing_values']} | {row['duplicate_rows']} |"
                for row in overview_rows
            ],
        ]
    )
    markdown_path.write_text(
        "\n".join(
            [
                "# Corpus analysis",
                "",
                "Generated by `scripts/analyze_corpus.py`.",
                "",
                "## Overview",
                "",
                overview,
                "",
                "## TechQA duplicates",
                "",
                f"- Duplicate groups: {summary['techqa']['duplicate_groups']}",
                f"- Removable duplicate rows: "
                f"{summary['techqa']['duplicate_rows_removed']}",
                f"- Cross-split duplicate groups: "
                f"{summary['techqa']['cross_split_duplicate_groups']}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    figure, axes = plt.subplots(1, 3, figsize=(18, 5))
    axes[0].hist(frames["techqa_qa"]["question_length"], bins=30)
    axes[1].hist(frames["techqa_qa"]["answer_length"], bins=30)
    axes[2].hist(frames["techqa_documents"]["document_length"], bins=30)
    axes[0].set_title("TechQA question lengths")
    axes[1].set_title("TechQA answer lengths")
    axes[2].set_title("TechQA document lengths")
    figure.tight_layout()
    figure.savefig(lengths_path, dpi=150)
    plt.close(figure)

    figure, axes = plt.subplots(1, 2, figsize=(18, 7))
    frames["bitext"]["category"].value_counts().sort_values().plot.barh(ax=axes[0])
    frames["bitext"]["intent"].value_counts().sort_values().plot.barh(ax=axes[1])
    axes[0].set_title("Bitext tickets by category")
    axes[1].set_title("Bitext tickets by intent")
    figure.tight_layout()
    figure.savefig(bitext_path, dpi=150)
    plt.close(figure)
    return [json_path, markdown_path, lengths_path, bitext_path]


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        summary, frames = analyze_corpora(args.data_dir)
        outputs = write_analysis(args.output_dir, summary, frames)
    except (FileNotFoundError, KeyError, ValueError) as exc:
        print(f"error: {exc}")
        return 1
    for path in outputs:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
