---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify_intent(classify_intent)
	retrieve(retrieve)
	generate(generate)
	clarification(clarification)
	escalate(escalate<hr/><small><em>__interrupt = before</em></small>)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify_intent;
	classify_intent -.-> clarification;
	classify_intent -.-> escalate;
	classify_intent -.-> generate;
	classify_intent -.-> retrieve;
	retrieve --> generate;
	clarification --> __end__;
	escalate --> __end__;
	generate --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
